server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forest_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  #mapper配置文件
  mapper-locations: classpath*:com.blog.myblog.mapper/*.xml
  type-aliases-package: com.blog.myblog.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      blog:
        myblog:
          mapper: debug
          service: info
          controller: info

myblog:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: myblog
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token


