server:
  port: 8080

spring:
  main:
    allow-circular-references: true

logging:
  level:
    com:
      blog:
        myblog:
          mapper: debug
          service: info
          controller: info